version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: schoolsdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
